### ISSUE TITLE
Support nested lists and ordered lists

### ISSUE THREAD

**Issue by aem** [aem/docs-soap#2]
Currently this only supports unordered lists and all bullets will be flattened to a depth of 0. We should both support ordered lists and bullets shouldn't be flattened.

**Comment by LeZuse** [comment]
@aem I am looking into this. Do you have any specifics in mind about the implementation?

**Comment by aem** [comment]
@LeZuse not at all, feel free to refactor as needed. the current list implementation was built specifically for the editor this library was originally written for, which (at the time) didn't support nested or ordered lists

**Comment by aem** [comment]
published in 0.1.4
