### ISSUE TITLE
Line Breaks Get Stripped

### ISSUE THREAD

**Issue by gregziegan** [aem/docs-soap#21]
**Provide a detailed description of the issue**
`<br>` tags are removed and, I believe, replaced with `<span>` tags.

**Steps to reproduce**
1. Copy something like

```
There's

missing

breaks
```

from Google Docs
2. Run the HTML through docsSoap
3. Either read the HTML or insert it into a contenteditable

**Expected behavior**
Linebreaks are preserved

**Actual behavior**
`<br>` is not preserved

**Code example or screenshot if applicable**
Here's where I think brs are managed:
https://github.com/aem/docs-soap/blob/master/src/docsSoap.js#L109

@aem

**Comment by aem** [comment]
@thebritican published in 0.1.6, live on NPM now
