### ISSUE TITLE
Package is ES6 in NPM.

### ISSUE THREAD

**Issue by jonzlin95** [aem/docs-soap#30]
**Provide a detailed description of the issue**

Code is compiled to ES6 in Npm package, but I noticed your webpack build doesn't do this. Not actually a problem, but it makes it a bit hard to install with certain webpack setups (Uglifying the package), in particular "create-react-app"

The fix is to add in package.json 

`"build-lib": "babel src --out-dir lib --plugins=transform-flow-strip-types",`

becomes

`"build-lib": "babel src --out-dir lib --plugins=transform-flow-strip-types" --presets=es2015,`

Or you can add a .babelrc

and to install

`npm install --save-dev babel-preset-es2015`

and finally edit index.js to be ES5 compliant - ie. (fix the `{ docsSoap }` shorthand to `{ docsSoap: docsSoap }`)

@aem - Thanks a bunch for your work mate :). Really helpful

**Comment by aem** [comment]
Thanks for pointing this out! I knew I had made the build ES6 but hadn't seen anyone who needed the ES5 build so I left it. I'll get to this either today or tomorrow and release a new version!

**Comment by jonzlin95** [comment]
Appreciate the quick response mate. Thanks for the great work :). 

ES5 build is useful because create-react-app (which is probably the most popular starter pack around) doesn't support ES6 packages :(. Ended up hacking an installation from a github fork for now.

**Comment by aem** [comment]
If you want to submit a PR from your fork I can merge it!

**Comment by aem** [comment]
1.2.0 is out! 🚀 https://github.com/aem/docs-soap/tree/v1.2.0
